class ListMusic {
  final int idMusic;
  final String photoMusic;
  final String filePath;
  final String nameArtiste;
  final String titreMusic;
  final String tempsMusic;
  final String hoursPost;
  final String vuePost;
  final String lickerPost;
  final String commentPost;

  ListMusic({
    required this.idMusic,
    required this.photoMusic,
    required this.filePath,
    required this.nameArtiste,
    required this.titreMusic,
    required this.tempsMusic,
    required this.hoursPost,
    required this.vuePost,
    required this.lickerPost,
    required this.commentPost
  });

  static List<ListMusic> listMusic = [
    ListMusic(
      idMusic: 1,
      photoMusic: 'assets/abdoull.jpg',
      filePath: 'assets/Dr_Keb_-_Tonight(256k).mp3',
      nameArtiste: 'Abdoul Prod ',
      titreMusic: 'Tonights',
      tempsMusic: '04:30',
      hoursPost: 'Il y\'a 1 seconde',
      vuePost: '20.0k',
      lickerPost: '26k',
      commentPost: '206',
    ),
    ListMusic(
      idMusic: 2,
      photoMusic: 'assets/drkeb.jpg',
      filePath: 'assets/MYLMO_Ft._DR_KEB_-_SAMBA__2021_.MP3',
      nameArtiste: 'Milmo ft Dr keb',
      titreMusic: 'SAMBA',
      tempsMusic: '04:30',
      hoursPost: 'Il y\'a 1 seconde',
      vuePost: '20.0k',
      lickerPost: '26k',
      commentPost: '206',
    ),
    ListMusic(
      idMusic: 3,
      photoMusic: 'assets/lilZed_3.jpg',
      filePath: 'assets/Dr_keb_A_be_gnenabô_freeStyle_2020(256k).mp3',
      nameArtiste: 'Lil Zed',
      titreMusic: 'Couplet Kele',
      tempsMusic: '04:30',
      hoursPost: 'Il y\'a 1 seconde',
      vuePost: '20.0k',
      lickerPost: '26k',
      commentPost: '206',
    ),
    ListMusic(
      idMusic: 4,
      photoMusic: 'assets/seydou_1.jpg',
      filePath: 'assets/Dr_keb_A_be_gnenabô_freeStyle_2020(256k).mp3',
      nameArtiste: 'Seydou Che',
      titreMusic: 'Ex',
      tempsMusic: '04:30',
      hoursPost: 'Il y\'a 1 seconde',
      vuePost: '20.0k',
      lickerPost: '26k',
      commentPost: '206',
    ),
    ListMusic(
      idMusic: 5,
      photoMusic: 'assets/seydou_2.jpeg',
      filePath: 'assets/Dr_keb_A_be_gnenabô_freeStyle_2020(256k).mp3',
      nameArtiste: 'Seydou chee',
      titreMusic: 'Couplet Kele',
      tempsMusic: '04:30',
      hoursPost: 'Il y\'a 1 seconde',
      vuePost: '20.0k',
      lickerPost: '26k',
      commentPost: '206',
    ),
    ListMusic(
      idMusic: 5,
      photoMusic: 'assets/lilZed_2.jpg',
      filePath: 'assets/Dr_keb_A_be_gnenabô_freeStyle_2020(256k).mp3',
      nameArtiste: 'Lil Zed 22',
      titreMusic: 'Couplet Kele',
      tempsMusic: '04:30',
      hoursPost: 'Il y\'a 1 seconde',
      vuePost: '20.0k',
      lickerPost: '26k',
      commentPost: '206',
    ),
  ];

}

/*
final List listMusic = [
    {
      "photoMusic": 'assets/abdoull.jpg',
      "nameArtiste": 'Abdoul Prod ',
      "titreMusic": 'femme de valeur',
      "tempsMusic": '04:30',
      "hoursPost": 'Il y\'a 1 seconde',
      "vuePost": '20.0k',
      "lickerPost": '26k',
      "commentPost": '206',
    },
    {
      "photoMusic": 'assets/abdoull-2.jpg.jpeg',
      "nameArtiste": 'Dr Keb',
      "titreMusic": 'Today',
      "tempsMusic": '03:02',
      "hoursPost": 'Il y\'a 1 minutes',
      "vuePost": '2k',
      "lickerPost": '600',
      "commentPost": '56',
    },
    {
      "photoMusic": 'assets/abdoull.jpg',
      "nameArtiste": 'Lil Zed',
      "titreMusic": 'COUPLET KELE',
      "tempsMusic": '02:16',
      "hoursPost": 'Il y\'a 2 semaines',
      "vuePost": '100.1k',
      "lickerPost": '30.9k',
      "commentPost": '12.0k',
    },
    {
      "photoMusic": 'assets/abdoull-2.jpg.jpeg',
      "nameArtiste": 'Malakey',
      "titreMusic": 'Réalité',
      "tempsMusic": '02:32',
      "hoursPost": 'Il y\'a 3 semaines',
      "vuePost": '1.1k',
      "lickerPost": '30',
      "commentPost": '12',
    },
    {
      "photoMusic": 'assets/abdoull.jpg',
      "nameArtiste": 'Buch Kp',
      "titreMusic": 'Médeline',
      "tempsMusic": '02:16',
      "hoursPost": 'Il y\'a 1 mois',
      "vuePost": '1.5k',
      "lickerPost": '200',
      "commentPost": '90',
    },
    {
      "photoMusic": 'assets/abdoull-2.jpg.jpeg',
      "nameArtiste": 'Oude Mill',
      "titreMusic": 'Today',
      "tempsMusic": '03:03',
      "hoursPost": 'Il y\'a 3 minutes',
      "vuePost": '2k',
      "lickerPost": '600',
      "commentPost": '56',
    },
    {
      "photoMusic": 'assets/abdoull.jpg',
      "nameArtiste": 'Abdoul Prod ',
      "titreMusic": 'femme de valeur',
      "tempsMusic": '04:30',
      "hoursPost": 'Il y\'a 1 seconde',
      "vuePost": '20.0k',
      "lickerPost": '26k',
      "commentPost": '206',
    },
    {
      "photoMusic": 'assets/abdoull-2.jpg.jpeg',
      "nameArtiste": 'Dr Keb',
      "titreMusic": 'Today',
      "tempsMusic": '03:02',
      "hoursPost": 'Il y\'a 1 minutes',
      "vuePost": '2k',
      "lickerPost": '600',
      "commentPost": '56',
    },
    {
      "photoMusic": 'assets/abdoull.jpg',
      "nameArtiste": 'Lil Zed',
      "titreMusic": 'COUPLET KELE',
      "tempsMusic": '02:16',
      "hoursPost": 'Il y\'a 2 semaines',
      "vuePost": '100.1k',
      "lickerPost": '30.9k',
      "commentPost": '12.0k',
    },
    {
      "photoMusic": 'assets/abdoull-2.jpg.jpeg',
      "nameArtiste": 'Malakey',
      "titreMusic": 'Réalité',
      "tempsMusic": '02:32',
      "hoursPost": 'Il y\'a 3 semaines',
      "vuePost": '1.1k',
      "lickerPost": '30',
      "commentPost": '12',
    },
    {
      "photoMusic": 'assets/abdoull.jpg',
      "nameArtiste": 'Buch Kp',
      "titreMusic": 'Médeline',
      "tempsMusic": '02:16',
      "hoursPost": 'Il y\'a 1 mois',
      "vuePost": '1.5k',
      "lickerPost": '200',
      "commentPost": '90',
    },
    {
      "photoMusic": 'assets/abdoull-2.jpg.jpeg',
      "nameArtiste": 'Oude Mill',
      "titreMusic": 'Today',
      "tempsMusic": '03:03',
      "hoursPost": 'Il y\'a 3 minutes',
      "vuePost": '2k',
      "lickerPost": '600',
      "commentPost": '56',
    },
    {
      "photoMusic": 'assets/abdoull.jpg',
      "nameArtiste": 'Abdoul Prod ',
      "titreMusic": 'femme de valeur',
      "tempsMusic": '04:30',
      "hoursPost": 'Il y\'a 1 seconde',
      "vuePost": '20.0k',
      "lickerPost": '26k',
      "commentPost": '206',
    },
    {
      "photoMusic": 'assets/abdoull-2.jpg.jpeg',
      "nameArtiste": 'Dr Keb',
      "titreMusic": 'Today',
      "tempsMusic": '03:02',
      "hoursPost": 'Il y\'a 1 minutes',
      "vuePost": '2k',
      "lickerPost": '600',
      "commentPost": '56',
    },
    {
      "photoMusic": 'assets/abdoull.jpg',
      "nameArtiste": 'Lil Zed',
      "titreMusic": 'COUPLET KELE',
      "tempsMusic": '02:16',
      "hoursPost": 'Il y\'a 2 semaines',
      "vuePost": '100.1k',
      "lickerPost": '30.9k',
      "commentPost": '12.0k',
    },
    {
      "photoMusic": 'assets/abdoull-2.jpg.jpeg',
      "nameArtiste": 'Malakey',
      "titreMusic": 'Réalité',
      "tempsMusic": '02:32',
      "hoursPost": 'Il y\'a 3 semaines',
      "vuePost": '1.1k',
      "lickerPost": '30',
      "commentPost": '12',
    },
    {
      "photoMusic": 'assets/abdoull.jpg',
      "nameArtiste": 'Buch Kp',
      "titreMusic": 'Médeline',
      "tempsMusic": '02:16',
      "hoursPost": 'Il y\'a 1 mois',
      "vuePost": '1.5k',
      "lickerPost": '200',
      "commentPost": '90',
    },
    {
      "photoMusic": 'assets/abdoull-2.jpg.jpeg',
      "nameArtiste": 'Oude Mill',
      "titreMusic": 'Today',
      "tempsMusic": '03:03',
      "hoursPost": 'Il y\'a 3 minutes',
      "vuePost": '2k',
      "lickerPost": '600',
      "commentPost": '56',
    },
    {
      "photoMusic": 'assets/abdoull.jpg',
      "nameArtiste": 'Abdoul Prod ',
      "titreMusic": 'femme de valeur',
      "tempsMusic": '04:30',
      "hoursPost": 'Il y\'a 1 seconde',
      "vuePost": '20.0k',
      "lickerPost": '26k',
      "commentPost": '206',
    },
    {
      "photoMusic": 'assets/abdoull-2.jpg.jpeg',
      "nameArtiste": 'Dr Keb',
      "titreMusic": 'Today',
      "tempsMusic": '03:02',
      "hoursPost": 'Il y\'a 1 minutes',
      "vuePost": '2k',
      "lickerPost": '600',
      "commentPost": '56',
    },
    {
      "photoMusic": 'assets/abdoull.jpg',
      "nameArtiste": 'Lil Zed',
      "titreMusic": 'COUPLET KELE',
      "tempsMusic": '02:16',
      "hoursPost": 'Il y\'a 2 semaines',
      "vuePost": '100.1k',
      "lickerPost": '30.9k',
      "commentPost": '12.0k',
    },
    {
      "photoMusic": 'assets/abdoull-2.jpg.jpeg',
      "nameArtiste": 'Malakey',
      "titreMusic": 'Réalité',
      "tempsMusic": '02:32',
      "hoursPost": 'Il y\'a 3 semaines',
      "vuePost": '1.1k',
      "lickerPost": '30',
      "commentPost": '12',
    },
    {
      "photoMusic": 'assets/abdoull.jpg',
      "nameArtiste": 'Buch Kp',
      "titreMusic": 'Médeline',
      "tempsMusic": '02:16',
      "hoursPost": 'Il y\'a 1 mois',
      "vuePost": '1.5k',
      "lickerPost": '200',
      "commentPost": '90',
    },
    {
      "photoMusic": 'assets/abdoull-2.jpg.jpeg',
      "nameArtiste": 'Oude Mill',
      "titreMusic": 'Today',
      "tempsMusic": '03:03',
      "hoursPost": 'Il y\'a 3 minutes',
      "vuePost": '2k',
      "lickerPost": '600',
      "commentPost": '56',
    },
  ];
 */
