const List video_data = [
  {
    "id": 1,
    "Clip_img": "assets/abdoull.jpg",
    "nomArtist": "Abdoul Prod",
    "titreClip": "Goumain Bana ",
    "heureClipDisponible": "Il y a 1 minute",
    "view_count": "5,521,419",
    //"day_ago": "Jun 29, 2018",
    "like_count": "511.6 k",
    "unlike_count": "37K",
    "video_url": "assets/video/video_1.mp4",
  },
  {
    "id": 2,
    "Clip_img": "assets/drkeb.jpg",
    "nomArtist": "Dr Keb",
    "titreClip": "Kana",
    "heureClipDisponible": "Il y a 2 minute",
    "view_count": "8,521,419",
    //"day_ago": "Jun 29, 2018",
    "like_count": "611K",
    "unlike_count": "17.1K",
    "video_url": "assets/video/video_2.mp4",
  },
  {
    "id": 3,
    "Clip_img": "assets/lilZed_3.jpg",
    "nomArtist": "Lil Zed",
    "titreClip": "Kana",
    "heureClipDisponible": "Il y a 2 minute",
    "view_count": "8,521,419",
    //"day_ago": "Jun 29, 2018",
    "like_count": "611K",
    "unlike_count": "17.1K",
    "video_url": "assets/video/video_2.mp4",
  },
  {
    "id": 4,
    "Clip_img": "assets/seydou_1.jpg",
    "nomArtist": "Seydou Ché",
    "titreClip": "Kana",
    "heureClipDisponible": "Il y a 2 minute",
    "view_count": "8,521,419",
    //"day_ago": "Jun 29, 2018",
    "like_count": "611K",
    "unlike_count": "17.1K",
    "video_url": "assets/video/video_2.mp4",
  },
];